namespace FluentFlow.Core.Code;

public static class PropertyConst
{
    public static readonly Dictionary<CSharpTypes, string> TypeNames = new Dictionary<CSharpTypes, string>
    {
        { CSharpTypes.Bool, "bool" },
        { CSharpTypes.Byte, "byte" },
        { CSharpTypes.SByte, "sbyte" },
        { CSharpTypes.Char, "char" },
        { CSharpTypes.Decimal, "decimal" },
        { CSharpTypes.Double, "double" },
        { CSharpTypes.Single, "float" },
        { CSharpTypes.Int, "int" },
        { CSharpTypes.UInt, "uint" },
        { CSharpTypes.Long, "long" },
        { CSharpTypes.ULong, "ulong" },
        { CSharpTypes.Short, "short" },
        { CSharpTypes.UShort, "ushort" },
        { CSharpTypes.String, "string" },
        { CSharpTypes.DateTime, "DateTime" },
        { CSharpTypes.TimeSpan, "TimeSpan" },
        { CSharpTypes.Guid, "Guid" },
        { CSharpTypes.Object, "object" },
        { CSharpTypes.NullableBool, "bool?" },
        { CSharpTypes.NullableByte, "byte?" },
        { CSharpTypes.NullableSByte, "sbyte?" },
        { CSharpTypes.NullableChar, "char?" },
        { CSharpTypes.NullableDecimal, "decimal?" },
        { CSharpTypes.NullableDouble, "double?" },
        { CSharpTypes.NullableSingle, "float?" },
        { CSharpTypes.NullableInt, "int?" },
        { CSharpTypes.NullableUInt, "uint?" },
        { CSharpTypes.NullableLong, "long?" },
        { CSharpTypes.NullableULong, "ulong?" },
        { CSharpTypes.NullableShort, "short?" },
        { CSharpTypes.NullableUShort, "ushort?" },
        { CSharpTypes.NullableDateTime, "DateTime?" },
        { CSharpTypes.NullableTimeSpan, "TimeSpan?" },
        { CSharpTypes.NullableGuid, "Guid?" }
    };

    public static readonly Dictionary<string, CSharpTypes> Types = new Dictionary<string, CSharpTypes>
    {
        { "bool", CSharpTypes.Bool },
        { "byte", CSharpTypes.Byte },
        { "sbyte", CSharpTypes.SByte },
        { "char", CSharpTypes.Char },
        { "decimal", CSharpTypes.Decimal },
        { "double", CSharpTypes.Double },
        { "float", CSharpTypes.Single },
        { "int", CSharpTypes.Int },
        { "uint", CSharpTypes.UInt },
        { "long", CSharpTypes.Long },
        { "ulong", CSharpTypes.ULong },
        { "short", CSharpTypes.Short },
        { "ushort", CSharpTypes.UShort },
        { "string", CSharpTypes.String },
        { "DateTime", CSharpTypes.DateTime },
        { "TimeSpan", CSharpTypes.TimeSpan },
        { "Guid", CSharpTypes.Guid },
        { "object", CSharpTypes.Object },
        { "bool?", CSharpTypes.NullableBool },
        { "byte?", CSharpTypes.NullableByte },
        { "sbyte?", CSharpTypes.NullableSByte },
        { "char?", CSharpTypes.NullableChar },
        { "decimal?", CSharpTypes.NullableDecimal },
        { "double?", CSharpTypes.NullableDouble },
        { "float?", CSharpTypes.NullableSingle },
        { "int?", CSharpTypes.NullableInt },
        { "uint?", CSharpTypes.NullableUInt },
        { "long?", CSharpTypes.NullableLong },
        { "ulong?", CSharpTypes.NullableULong },
        { "short?", CSharpTypes.NullableShort },
        { "ushort?", CSharpTypes.NullableUShort },
        { "DateTime?", CSharpTypes.NullableDateTime },
        { "TimeSpan?", CSharpTypes.NullableTimeSpan },
        { "Guid?", CSharpTypes.NullableGuid }
    };

    public static readonly Dictionary<CSharpTypes, string> TypeMappings = new Dictionary<CSharpTypes, string>()
    {
        { CSharpTypes.String, "AsString" },
        { CSharpTypes.Bool, "AsBoolean" },
        { CSharpTypes.Byte, "AsByte" },
        { CSharpTypes.SByte, "AsSByte" },
        { CSharpTypes.Decimal, "AsDecimal" },
        { CSharpTypes.Double, "AsDouble" },
        { CSharpTypes.Single, "AsFloat" },
        { CSharpTypes.Guid, "AsGuid" },
        { CSharpTypes.Short, "AsInt16" },
        { CSharpTypes.Int, "AsInt32" },
        { CSharpTypes.Long, "AsInt64" },
        { CSharpTypes.UShort, "AsUInt16" },
        { CSharpTypes.UInt, "AsUInt32" },
        { CSharpTypes.ULong, "AsUInt64" },
        { CSharpTypes.Char, "AsChar" },
        { CSharpTypes.NullableDateTime, "AsDateTime" },
        { CSharpTypes.NullableTimeSpan, "AsTime" },
        { CSharpTypes.NullableGuid, "AsGuid" },
        { CSharpTypes.NullableBool, "AsBoolean" }
    };

    public enum CSharpTypes
    {
        Bool,
        Byte,
        SByte,
        Char,
        Decimal,
        Double,
        Single,
        Int,
        UInt,
        Long,
        ULong,
        Short,
        UShort,
        String,
        DateTime,
        TimeSpan,
        Guid,
        Object,
        NullableBool,
        NullableByte,
        NullableSByte,
        NullableChar,
        NullableDecimal,
        NullableDouble,
        NullableSingle,
        NullableInt,
        NullableUInt,
        NullableLong,
        NullableULong,
        NullableShort,
        NullableUShort,
        NullableDateTime,
        NullableTimeSpan,
        NullableGuid
    }
}